#!/bin/sh

### Custom user script
### Called after internal WAN up/down action
### $1 - WAN action (up/down)
### $2 - WAN interface name (e.g. eth3 or ppp0)
### $3 - WAN IPv4 address

case "$1" in
up)
vCron="/etc/storage/cron/crontabs/admin"
vOn=`grep "led.sh \{1,\}-ON" $vCron 2>/dev/null|awk '{print $2*60+$1}'`
vOff=`grep "led.sh \{1,\}-OFF" $vCron 2>/dev/null|awk '{print $2*60+$1}'`

if [ "$vOn" = "" ] || [ "$vOff" = "" ]; then
	vCur=0
	vOn=0
	vOff=1
else
	vOff=$(expr $vOff - $vOn )
	while [ $vOff -le 0 ]; do
		vOff=$((vOff+24*60))
	done

	vCur=$(expr `date +%H` \* 60 + `date +%M` - $vOn)
	while [ $vCur -lt 0 ]; do
		vCur=$((vCur+24*60))
	done
fi

if [ $vCur -lt $vOff ]; then
	/etc/storage/led.sh blue "Internet已连接，开启蓝灯"
else
	/etc/storage/led.sh -OFF "Internet已连接，关闭指示灯"
fi

#/usr/bin/unblockmusic.sh restart
;;

down)
/etc/storage/led.sh yellow "Internet未连接，开启黄灯"
;;

*)
;;
esac
